import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/page";
import {Roboto} from "next/font/google"
import {Work_Sans} from "next/font/google"


const roboto =  Roboto({
  weight: "800",
  subsets:["latin"],
  variable: "--font-robot"
})
const workSans =  Work_Sans({
  subsets:["latin"],
  variable: "--font-work-sans"
})


export const metadata: Metadata = {
  title: "Next.Js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${workSans.variable}`} >
        <Navbar />
        {children}
        </body>
    </html>
  );
}
